### ISSUE TITLE
QE-147 Include error message with failed (flaky?) tests

### ISSUE THREAD

**Issue by Dan-DeAraujo** [Brightspace/test-reporting-node#149] opened 2024-03-11 20:17 UTC
Would help understand test failure reason trends, and we can focus de-flaking efforts on areas of higher impact.

EG: [This run](https://test-automation-results.d2l.dev/playwright/playwright-ui-automation/2024-03-11/8235117787/playwright-report/@grades/firefox/#?testId=02cd00bf9dacccb5edd0-a8b6e1e4bcc4b34da54f) failed with `Error: locator.fill: Target page, context or browser has been closed`; which is clearly not something we can resolve directly, but if we notice an uptick post-Playwright update, we can complain to them about it

OTOH, if we notice alot of tests failing to find locators or whatever, maybe we need better training on how to pick good ones

Not sure if we can get it for flaky tests (ie: the first run of a retried set) too, but if we can that'd be even better

**Comment by devpow112** [comment] 2024-03-11 20:21
Duplicate of https://github.com/Brightspace/test-reporting-node/issues/87.

**Comment by devpow112** [comment] 2024-05-02 20:34
Gonna try and send error `message`, `file`, `line` and `column` values for each test when an error occurs. For retired tests I'm just gonna send the last error for now. If we find we need all error information or something else we can explore that separately.

**Comment by devpow112** [comment] 2024-07-19 14:55
Moved to Jira

**Closed** 2024-07-19 14:56 UTC
